### ISSUE TITLE
Project needs a changelog

### ISSUE THREAD

**Issue by asachs01** [sensu/web#189]
## Feature Suggestion

From a user perspective and from the perspective of someone who has to support users, it would be REALLY useful to have a changelog introduced to the project. The Sensu Go project itself has a changelog, but web changes don't appear to be a part of that.

**Comment by jamesdphillips** [comment]
It would be interesting to provide a changelog, however, since the web app itself isn't versioned or independently packaged I fear that it would only be a never ending list of changes. If anything, it would likely even be less compelling than simply viewing the [commit log](https://github.com/sensu/web/commits/master).

I'm not sure if this helps but, when the web app is vendor'd into `sensu-go` I do update sensu-go's CHANGELOG; said entries are prefixed with `[Web]`. For example in the last release:

<img width="889" alt="Screen Shot 2019-09-04 at 12 05 39 PM" src="https://user-images.githubusercontent.com/194892/64283465-5b4f6d80-cf0c-11e9-8b54-daa0cf56e742.png">

---

@asachs01 if `sensu/web` were to have a CHANGELOG that linked to `sensu-go`'s CHANGELOG with a brief explanation, would that satisfy your use case?

**Comment by asachs01** [comment]
Oh! I hadn't actually looked at the Sensu Go changelog @jamesdphillips . My apologies! I think we may have just missed this when we were working on release notes. Lemme chat with the team and confirm that this was the case.

**Comment by jamesdphillips** [comment]
@asachs01 do you feel this has been working out? If the sensu-go changelog has been working out I would like to close this issue out.

**Comment by asachs01** [comment]
I believe that it has @jamesdphillips . We can close this out.
