### ISSUE TITLE
Ad-hoc execution for proxy checks not working / cannot match proxy entities

### ISSUE THREAD

**Issue by becon-cmichel** [sensu/web#37]
Ad-hoc execution of "normal" checks via the dashboard is working as expected. But the ad-hoc execution of proxy checks isn't. The message in the log is:

sensu-backend[36878]: {"check":"proxy-check-example","component":"schedulerd","level":"warning","msg":"no matching entities, check will not be published","namespace":"default","time":"2019-03-19T13:35:25+01:00"}

## Expected Behavior
Ad-hoc execution of proxy checks via the dashboard will cause that all matching entities executes the check. 

## Current Behavior
Ad-hoc execution of proxy checks via the dashboard could not match any entity. 

## Steps to Reproduce (for bugs)
1. create proxy check
2. create proxy entity
3. run ad-hoc execution via the dashboard
4. look into the log of sensu-backend

## Your Environment
* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): version 5.3.0#379593a, build 379593a8859315e746da28eedfdc8ae4907091fa, built 2019-03-07T19:00:37Z
* Installation method (packages, binaries, docker etc.): packages
* Operating System and version (e.g. Ubuntu 14.04): Debian GNU/Linux 9.8 (stretch)

**Comment by wesleycyu** [comment]
The “re-run” button used of ad-hoc executions is not supposed to work for proxy entities. Including the “re-run” button for a proxy entity check on the Check Results screen in the UI an oversight on our part. Our intention in an upcoming release is to remove/disable the “re-run” button on that screen.

We don’t preform check re-runs against proxy entities because to do so we would need to re-run the check against all its subscriptions. We believe that, as a user, clicking re-run on a check and having the check run against all subscriptions is not expected behaviour, and could lead to unwanted results.

In the future, we may implement a dialogue that would allow the user to select which subscriptions a check is run against, so that users have more control over what happens when a check is re-run. However, for the time being, we are going to remove the “re-run” button from the Check Results screen for proxy entity checks.
